
custom:
  demo:
    enabled: true
jdbc:
  mysql:
    url: jdbc:mysql://localhost:3306/geek?serverTimezone=Asia/Shanghai
    username: root
    password: '00000000'
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/geek?serverTimezone=Asia/Shanghai
#    username: root
#    password: '00000000'
#    hikari:
#      pool-name: HikariPool
#      maximum-pool-size: 10
#      minimum-idle: 2
#      connection-timeout: 20000
#      connection-test-query: SELECT 1
#      idle-timeout: 500000

