jdbc:
  mysql:
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: '00000000'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: '00000000'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 30
      minimum-idle: 2
      connection-timeout: 20000
      connection-test-query: SELECT 1
      idle-timeout: 500000
      validation-timeout: 3000
    type: com.zaxxer.hikari.HikariDataSource
